name: Build on Tag

on:
  push:
    tags: '*'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v3

    - name: Download File
      run: |
        wget -O AlphaDroid-13.0-20230615-merlinx-full_gapps-v1.5.1.zip https://sourceforge.net/projects/rom-builders/files/merlinx/AlphaDroid-13.0-20230615-merlinx-full_gapps-v1.5.1.zip/download

    - name: Cek File
      run: ls

    - name: Create Draft Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.5.1
        release_name: AlphaDroid
        draft: true
        prerelease: false

    - uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./AlphaDroid-13.0-20230615-merlinx-full_gapps-v1.5.1.zip
        asset_name: AlphaDroid-13.0-20230615-merlinx-full_gapps-v1.5.1.zip
        asset_content_type: application/zip

    - uses: eregon/publish-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ steps.create_release.outputs.id }}
