name: Build on Tag

on:
  push:
    tags: '*'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v3

    - name: Download File
      run: |
        wget -O AlphaDroid-13.0-20230611-merlinx-PIXEL-v1.5.1.zip https://sourceforge.net/projects/rom-builders/files/merlinx/AlphaDroid-13.0-20230611-merlinx-full_gapps-v1.5.1.zip/download

    - name: Cek File
      run: ls

    - name: Release build
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ./*.zip
        token: ${{ secrets.GITHUB_TOKEN }}


# This is a basic workflow to help you get started with Actions

name: CI Uploader

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    tags: '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Download File
        run: |
          wget -O AlphaDroid-13.0-20230611-merlinx-PIXEL-v1.5.1.zip https://sourceforge.net/projects/rom-builders/files/merlinx/AlphaDroid-13.0-20230611-merlinx-full_gapps-v1.5.1.zip/download

      - name: Release build
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: ./AlphaDroid-13.0-20230611-merlinx-PIXEL-v1.5.1.zip
          token: ${{ secrets.GITHUB_TOKEN }} 