# This is a basic workflow to help you get started with Actions

name: CI Uploader

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Runs a single command using the runners shell
      - name: Install Requirement
        run: |
          wget https://github.com/TheCaduceus/tg-upload/archive/refs/tags/v1.0.9.zip
          unzip *.zip
          cd tg-upload*
          pip install -r requirements.txt
          python tg-upload.py -h
          ls
          pwd

      # Runs a set of commands using the runners shell
      - name: Download File
        run: |
          wget -O AlphaDroid-13.0-20230611-merlinx-full_gapps-v1.5.1.zip https://sourceforge.net/projects/rom-builders/files/merlinx/AlphaDroid-13.0-20230611-merlinx-full_gapps-v1.5.1.zip/download

      - name: Upload File
        run: |
          pwd
          ls
          cd tg-upload*
          python tg-upload.py --bot 5241366125:AAGmyJDczdhciMypsKxWafJH6w0LfvSzYpE --path ../*.AlphaDroid-13.0-20230611-merlinx-full_gapps-v1.5.1.zip --chat_id 965784022
