name: Kyuun

on:
  workflow_dispatch:
    inputs:
      urls: 
        description: 'URL'
        required: true
      names:
        description: 'File Name'
        required: true
      releaseName:
        description: 'Release Name'
        required: true
      tagName:
        description: 'Tag Name'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v3

    - name: Download File
      run: |
        wget -O ${{ github.event.inputs.names }} ${{ github.event.inputs.urls }}

    - name: Cek File
      run: ls

    - name: Create Draft Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.tagName }}
        release_name: ${{ github.event.inputs.releaseName }}
        draft: true
        prerelease: false

    - uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./${{ github.event.inputs.names }}
        asset_name: ${{ github.event.inputs.names }}
        asset_content_type: application/zip

    - uses: eregon/publish-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ steps.create_release.outputs.id }}
