# This is a basic workflow to help you get started with Actions

name: Build Tester

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# ...

jobs:

  slim_build:

    runs-on: ubuntu-latest

    # You can use either of the ubuntu-20.04 or ubuntu-22.04 runner

    steps:

      # You might want to Checkout your repo first, but not mandatory

      - uses: actions/checkout@v3

      # Cleanup The Actions Workspace Using Custom Composite Run Actions

      - uses: rokibhasansagar/slimhub_actions@main

        # Optional key, "retain": Use only if you want something to keep

        with:

          retain: "apt,wget"

          # The values must match from the below list

      # That's it! Now use your normal steps

      - name: "Build Test"
        run: |
          echo "Test"
